First bash at adapting for use on any cluster

diff --git a/interactive b/interactive
--- a/interactive
+++ b/interactive
@@ -1,20 +1,18 @@
 #!/bin/bash
 
-# TODO: check if partition containing word interactive exists then try and run
-#       there - upon failure (or estimate in > 2 mins time) try using default
-#       partition. If too long, try interactive partition again and warn of
-#       wait.
+set -e
 
 # TODO: make a _gpu and non version
 
 default_args="--time=08:00:00 --mem=14000 --cpus-per-task=4 --gres=gpu:1"
+
 read -r -d '' default_msg << EOM
 =============================== WELCOME MESSAGE ===============================
 It's good practice to set a few parameters when using srun (this command is
 essentailly an alias for 'srun --pty bash'). We have added some default
 parameters to maximise your chance of getting an interactive session. See the
-Slurm Documentation for further info:
-    https://slurm.schedmd.com/
+Slurm Documentation for further info about parameters for srun:
+    https://slurm.schedmd.com/srun.html
 
 Default args added:
 [$default_args]
@@ -36,7 +34,7 @@ Useful arg examples:
                          get the full list of partitions, run "sinfo"
 
 For more informtion about node configuration, see the computing support docs:
-    http://computing.help.inf.ed.ac.uk/james-and-charles-cluster
+    http://computing.help.inf.ed.ac.uk/cluster-computing
 
 ===============================================================
 EOM
@@ -48,10 +46,6 @@ Usage: $0 [-h] [other args for srun]
 Arguments:
     -h
         Print a friendly starter for 10
-    -p PARTITION
-        The partition to use
-    -m WAIT_TIME
-        max time to wait before trying default partition. Default 10 seconds.
     [other args for srun]
         see documentation for srun:
             https://slurm.schedmd.com/srun.html
@@ -60,57 +54,55 @@ Arguments:
 EOM
 }
 
-max_wait=0.1
-while getopts 'hm:p:' flag; do
+
+while getopts 'h' flag; do
   case "${flag}" in
-    m) max_wait="${OPTARG}" ;;
     h) print_usage
        exit 1 ;;
   esac
 done
-shift $((OPTIND-1))
+
+
+get_interactive_session() {
+  srun_args=$@
+  echo
+  echo "Doing a --test-only to estimate wait time..."
+  srun ${srun_args} --test-only --pty bash
+  echo
+  echo "Running the following command to get you an interactive session:"
+  echo "srun ${srun_args} --pty bash"
+  echo "..."
+  srun ${srun_args} --pty bash
+}
+
 
 if [ $# -eq 0 ]; then
   args=$default_args
-  interactive_partitions=`sinfo -o %R -h | grep -i interactive`
-  if [ -z "$interactive_partitions" ]; then
-    echo "No partitions found with 'interactive' in their name"
-    echo "Attempting to get a session on the default partition"
-  fi
 else
-  # If the user supplies args, no defaults set
+  # If the user supplies args, don't set any default args 
   args=$@
+  get_interactive_session ${args}
+  exit 0  # <-------------- EXIT 1 (user specifies args)
 fi
 
+interactive_partitions=`sinfo -o %R -h | grep -i interactive`
 if [ -z "$interactive_partitions" ]; then
-  echo
-  echo "Doing a --test-only to estimate wait time..."
-  srun_test_out=$(srun $args --test-only --pty bash  2>&1 | tee /dev/tty)
-  echo
-  echo "Running the following command to get you an interactive session:"
-  echo "srun $args --pty bash"
-  echo "..."
-  srun $args --pty bash
+  echo "No partitions found with 'interactive' in their name"
+  echo "Attempting to get a session on the default partition"
+  get_interactive_session ${args}
+  exit 0  # <-------------- EXIT 2 (no args, no interactive partitions)
 else
+  succeeded=0
   for partition in $interactive_partitions"; do
-    partition="${interactive_partitions[$ii]}"
-    args="--partition=${partition} $args"
-    echo
-    echo "Doing a --test-only to estimate wait time..."
-    srun_test_out=$(srun $args --test-only --pty bash  2>&1 | tee /dev/tty)
-    echo
-    ## Not reliable to use the datetime in the end - reported datetime doesn't
-    ## match that reported by date '+%Y-%m-%dT%H:%M:%S'. Using 
-    # srun_dt=$(echo $srun_test_out | \
-    #           grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}')  
-
-    echo "Running the following command to get you an interactive session:"
-    echo "srun $args --pty bash"
-    echo "..."
-    srun $args --pty bash
+    get_interactive_session --partition=${partition} ${args} \
+      && succeeded=1 \
+      || true
+    if [ $succeeded -eq 1 ]; then
+      exit 0  # <-------------- EXIT 3 (no args, interactive partition found)
+    fi
   done
-  
+  # will only get here if all else fails:
+  #   tried interactive partitions, trying the default partition
+  get_interactive_session ${args}
+  exit 0  # <-------------- EXIT 4 (no args, int part found but default used)
 fi
-
-
-
