Tested and added examples

diff --git a/sinline b/sinline
--- a/sinline
+++ b/sinline
@@ -3,59 +3,80 @@
 print_usage () {
   cat << EOM
 
-Usage: $0 -n nodename [-s sbatch_args] command
+Usage: $0 -n nodename -c command [-s sbatch_args]
     Run a command and print the output to stout/stderr
 
 Arguments:
     -n nodename
         The name of the node to run the command on
+    -c command
+        The command to run wrapped as a string (sim to -c
+        argument submitted to python)
     -s sbatch_args
         Arguments to supply to sbatch wrapped as a string
     command
         The command exactly as you want to run in on the node
 
+Example call:
+    $ sinline -n charles01 -c 'echo "It'\''s so convenient!"' -s '--time=00:01:00 -p Interactive'
+        submitting batch job 123456
+        It's so convenient!    
+    
+    $ # Return space used on all noninteractive charles scratch disks 
+    $ for ii in {02..19}; do echo --------; echo charles$ii; sinline -n charles$ii -c 'du -sh /disk/scratch/*' 2>/dev/null | sort -rh ; done 
+
+
 EOM
 }
 
 node=''
+cmd=''
 sbatch_args=''
+
 # Parse args
-while getopts 'n:s:h' flag; do
+while getopts 'n:s:c:' flag; do
   case "${flag}" in
     n) node="${OPTARG}" ;;
     s) sbatch_args="${OPTARG}" ;;
-    h) print_usage
+    c) cmd="${OPTARG}" ;;
+    *) print_usage
        exit ;;
   esac
 done
 
-# Check a bash script supplied
+# Check a node is supplied
 if [ -z "${node}" ]; then
   echo "You must supply a node to run the command on"
   print_usage
   exit 1
 fi
 
-# Check a bash script supplied
-if [ -z "${sbatch_args}" ]; then
-  # On some clusters e.g. cdtcluster, time arg is compulsory for job to run
-  sbatch_args="--time=00:01:00"
+# Check a command supplied
+if [ -z "${cmd}" ]; then
+  echo "You must supply a command to run"
+  print_usage
+  exit 1
 fi
 
-# Set all remaining args as the command to run (supplied direct to sbatch)
-shift $((OPTIND -1))
-command="${@}"
+# Add default sbatch args if not specified 
+if [ -z "${sbatch_args}" ]; then
+  # On some clusters e.g. cdtcluster, time arg is compulsory for job to run
+  sbatch_args="--time=00:30:00"
+fi
 
-read -r -d '' bash_script << EOM
-#/bin/bash
-#SBATCH -o /tmp/sbatch_stdout.log
-#SBATCH -e /tmp/sbatch_sterr.log
-${command}
-EOM
+echo '#!/bin/bash' > /tmp/bash_script.sh 
+echo '#SBATCH -o sbatch_stdout.log' >> /tmp/bash_script.sh  
+echo '#SBATCH -e sbatch_stderr.log' >> /tmp/bash_script.sh  
+echo "${cmd}" >> /tmp/bash_script.sh
 
-echo "$bash_script" > /tmp/bash_script.sh
+# TODO: would it have been easier to use --wrap?
+sbatch --wait ${sbatch_args} -w ${node} /tmp/bash_script.sh
+wait
 
-sbatch ${sbatch_args} /tmp/bash_script.sh
+cat sbatch_stdout.log >&1
+cat sbatch_stderr.log >&2
 
-cat /tmp/sbatch_stdout.log >&1
-cat /tmp/sbatch_stderr.log >&2
+# Clean up
+rm sbatch_std{out,err}.log
+rm /tmp/bash_script.sh
+
